# Generated by Django 4.1.2 on 2022-11-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactlist_address_alter_contactlist_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='address',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
